# -*- coding: utf-8 -*-
"""Copy of NLP visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cODWMfZkGvygqpQX-hYCygITVXkAOpPy
"""

!mkdir data

!mkdir data/nlp

!curl ./data/nlp/Organizations.txt

data_path = "./data/nlp/Organizations.txt"

with open(data_path) as file:
    data = file.read()
print(data)

import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

tokens = nltk.word_tokenize(data)

tagged = nltk.pos_tag(tokens)

permitted_tags = set([
    'NN',
    'NNS'
])

fd = nltk.FreqDist()

for bit in tagged:
    if bit[1] in permitted_tags and len(bit[0])>2:
        fd[bit[0]] = fd[bit[0]] + 1
        
fd.plot(30)

list(fd.keys())[1:5]

list(fd.values())[1:5]

import pandas as pd
df = pd.DataFrame({'items': list(fd.keys()), 'counts': list(fd.values())})
df.head(10)

df = df.sort_values(by='counts', ascending=False)
df.head(20)

for word in ['welfare']:
    print(word, fd[word])

import matplotlib.pyplot as plt

plt.style.use('ggplot')
df[1:30].plot(kind='bar', x='items', y='counts', legend=False)
plt.xlabel('Word')
plt.ylabel('Word Count')
plt.title('Word counts for Wildlife Organizations Statements')
plt.axhline(df['counts'].mean(), color='#2222ff')